### ISSUE TITLE
Prediction output when layer is 0

### ISSUE THREAD

**Issue by katrina-liu** [JinsenLi/deepDNAshape#1]
Hi,

I am trying to use the model without considering any flanking effects. However, when I tried to use the model with layer 0, the output includes a list of the values for each position. For example, 
`[5.014357  5.068044  4.8264503 4.701848  4.7236924 4.7253203 4.723446
 4.723597 ] [5.014357  4.773773  4.335664  4.56145   4.612091  4.645525  4.6513386
 4.6536655] [4.9650784 4.5434246 4.887558  5.069393  5.040157  5.070367  5.081231
.......`

Is this supposed to be the actual output? If so, how should I interpret it? Thank you!

**Comment by JinsenLi** [comment]
The output should remain the same structure as other layers, however layer 0 has a different setup compared to other layers which I may have overlooked. I will fix it as soon as possible. 

BTW, note that layer 0 means 0 neighbors are considered. There will be only 2 possible values for A/T and C/G (intra-base pair features and groove features). For inter-base pair features such as Roll, only 10 possible values of di-nucleotides.

**Comment by JinsenLi** [comment]
This issue has been fixed.
