### ISSUE TITLE
Issue with File Input for DNA Shape Feature Prediction

### ISSUE THREAD

**Issue by biglittleme** [JinsenLi/deepDNAshape#2]
Dear deepDNAshape Maintainers,
I have encountered an error while attempting to predict DNA shape features using a file as input. The command I used was:
‘python deepDNAshape --file filetest1.txt --feature MGW’

results in a ValueError related to the truth value of an array being ambiguous. The traceback indicates that the issue arises within the predictBatch function, suggesting that there might be a problem with the processing of a RaggedTensor. Please refer to the attached screenshot for the full error message.
![DetailedInfo](https://github.com/JinsenLi/deepDNAshape/assets/77109380/ef8cd17d-8955-4d32-a59a-091a6baa6187)

I have ensured that the input file conforms to the format requirements specified in the README.md file and have tried several different forms of file input as mentioned in the documentation, but I encounter the same error each time.

Could you please advise on the possible causes of this error? Additionally, are there specific version requirements for TensorFlow and numpy for this tool? The versions I am currently using are TensorFlow 2.3.0 and numpy 1.19.2. Could this issue be due to a version incompatibility?

I appreciate any guidance you can provide on this matter and thank you in advance for your assistance.

**Comment by JinsenLi** [comment]
Thanks for your feedback. I tested this version of tensorflow and it didn't work. 

I updated the readme file and setup.py to specifily require a version of tensorflow>=2.6.0.

**Comment by biglittleme** [comment]
I apologize for any inconvenience this might cause, and I feel a bit foolish for having to ask, but I genuinely need assistance.

I encounter an error when executing 'python deepDNAshape --seq AAGGTT --feature MGW' after updating TensorFlow to version 2.6.0, which automatically installs NumPy version 1.24.3. The error message indicates an AttributeError related to the 'object' attribute in NumPy (the error trace is detailed in the attached screenshot). 
![image](https://github.com/JinsenLi/deepDNAshape/assets/77109380/824bc48b-7d2c-420f-9171-0e6e4913b108)

Attempting to resolve this by downgrading NumPy to version 1.19.5 leads to compatibility issues with TensorFlow 2.6.0.  I am currently stuck with this version conflict and am uncertain how to proceed.

Could you kindly provide guidance on the specific version requirements for TensorFlow and NumPy to ensure they are compatible with deepDNAshape? Is there a known resolution to this dilemma that I may have overlooked? Thanks so much!

**Comment by JinsenLi** [comment]
I tested tensorflow 2.6 with numpy 1.19.5, which should work. 

The numpy version of 1.24.3 is not compitable right now. If tensorflow 2.6 doesn't work, you can upgrade tensorflow to 2.13 and downgrade numpy to 1.22. I tested this combination and it works.

**Comment by biglittleme** [comment]
I appreciate the time and effort you took to help me resolve this issue. Best wishes!
